### ISSUE TITLE
M from Monday is | |

### ISSUE THREAD

**Issue by FLamorce** [aFewBits/stc-led-clock#13]
More cosmetic than other, but to display Monday, the "M" is "| |", why is there no bar at the top?

**Comment by aFewBits** [comment]
The fonts are a purely personal choice thing. To add the top bar, edit the file /segTable/segment_list.txt and change the line:

0x4D  bcef  ; M 
to:
0x4D  abcef  ; M 
and save.

Issue the command "make led" then "make" and it will be compiled with the change you mentioned.

**Comment by FLamorce** [comment]
thanks!
