### ISSUE TITLE
Blue Model with Relay on PCB - Cannot set clock

### ISSUE THREAD

**Issue by flyingsaucer0001** [aFewBits/stc-led-clock#6]
Here it is my model:
![schematic1](https://user-images.githubusercontent.com/12463245/38160859-19830152-34c4-11e8-92a8-cbed03d1aafa.jpg)

Now 1F:7F disappeared and I have 00:00 but I cannot set the clock, Display show temp in °C but It's showing Light Sensor data infact If I go dark in the room it shows 54-55°C, with neon light temp show variables value from 18° to 26° (it's reading light and showing as temp eheh)

Maybe also all DS1302 pins needs to be set to bidirectional.

Thanks for helping

**Comment by flyingsaucer0001** [comment]
You are my hero!!!!!! Finally it's working perfectly with your shining firmware :))))
I've configured global.h this way:
#define BOARD_TALKING      FALSE
#define BOARD_BLUE_6       FALSE
#define BOARD_BLUE_5_RELAY TRUE
#define BOARD_YELLOW_5     FALSE
#define BOARD_YELLOW_SMALL FALSE
#define BOARD_WHITE_SMALL  FALSE
#define BOARD_GREEN_SMALL  FALSE

#define COMMON_ANODE   TRUE
#define COMMON_CATHODE FALSE

#define PROC_IS_15W408AS FALSE
#define PROC_IS_15W404AS FALSE
#define PROC_IS_15F204EA TRUE

#define HAS_LDR TRUE
#define HAS_THERMISTOR TRUE
#define HAS_RELAY TRUE

#define DIGIT_3_FLIP TRUE

And finally look here:
![afewbits1](https://user-images.githubusercontent.com/12463245/38162110-def77a82-34db-11e8-8700-c4082e1fb530.jpg)
and here:
![afewbits2](https://user-images.githubusercontent.com/12463245/38162116-ebdbe512-34db-11e8-91cf-23141a8bf645.jpg)
Thanks thanks thanks

**Comment by aFewBits** [comment]
Please be sure to rebuild with the main.c file that shows as "Merge pull request #5 from Metori/chime_hours_fix". Another user was kind enough to fix a bug in the chime code that I merged after I posted the fix for the 15F204EA processor type. :relieved:
