### ISSUE TITLE
Talking Clock Led BLACK PCB

### ISSUE THREAD

**Issue by flyingsaucer0001** [aFewBits/stc-led-clock#8]
Hi! aFewBits
I've bought one of this: 
http://www.diyleyuan.com/JC/HJ1.html
I've configured this way:
#ifndef _GLOBAL_H
#define _GLOBAL_H

#define TRUE 1 // for general use, bit setters too
#define FALSE 0

#define FOSC 22118400L // clock speed in mhz
#define T0TICKS 20000 // Timer 0 tick rate (t) (1/t = 50us)
#define BAUD 115200 // debug serial baud rate
#define RxD2 P3_6 // UART only in 15W408AS
#define TxD2 P3_7 // use for debugging
#define DEBUG FALSE // set true for serial debugging

#define TICKS_MS 20 // This is set by Timer 1 tick rate
#define MAX_BRIGHT 63 // maximum tick count for brightness
#define MIN_BRIGHT 1 // minimum tick count for brightness

//---------------------------------------------------------------------------
// Begin Hardware Option configuration
//---------------------------------------------------------------------------

#define BOARD_TALKING TRUE
#define BOARD_BLUE_6 FALSE
#define BOARD_BLUE_5_RELAY FALSE
#define BOARD_YELLOW_5 FALSE
#define BOARD_YELLOW_SMALL FALSE
#define BOARD_WHITE_SMALL FALSE
#define BOARD_GREEN_SMALL FALSE

#define COMMON_ANODE TRUE
#define COMMON_CATHODE FALSE

#define PROC_IS_15W408AS TRUE
#define PROC_IS_15W404AS FALSE
#define PROC_IS_15F204EA FALSE

#define HAS_LDR TRUE
#define HAS_THERMISTOR TRUE
#define HAS_RELAY FALSE

#define DIGIT_3_FLIP TRUE

But I receive this...

mkdir -p build/
sdcc --iram-size 256 --code-size 8000 --data-loc 0x30 --disable-warning 158 -o build/adc.rel -c src/adc.c
mkdir -p build/
sdcc --iram-size 256 --code-size 8000 --data-loc 0x30 --disable-warning 158 -o build/ds1302.rel -c src/ds1302.c
mkdir -p build/
sdcc --iram-size 256 --code-size 8000 --data-loc 0x30 --disable-warning 158 -o build/timer.rel -c src/timer.c
mkdir -p build/
sdcc --iram-size 256 --code-size 8000 --data-loc 0x30 --disable-warning 158 -o build/display.rel -c src/display.c
mkdir -p build/
sdcc --iram-size 256 --code-size 8000 --data-loc 0x30 --disable-warning 158 -o build/utility.rel -c src/utility.c
mkdir -p build/
sdcc --iram-size 256 --code-size 8000 --data-loc 0x30 --disable-warning 158 -o build/serial.rel -c src/serial.c
mkdir -p build/
sdcc --iram-size 256 --code-size 8000 --data-loc 0x30 --disable-warning 158 -o build/sound.rel -c src/sound.c
src/sound.c:15: warning 112: function 'bcdToDec' implicit declaration
src/sound.c:16: warning 112: function 'bcdToDec' implicit declaration
src/sound.c:45: warning 112: function 'bcdToDec' implicit declaration
src/sound.c:46: warning 112: function 'bcdToDec' implicit declaration
src/sound.c:15: error 101: too many parameters
src/sound.c:16: error 101: too many parameters
src/sound.c:45: error 101: too many parameters
src/sound.c:46: error 101: too many parameters
Makefile:12: recipe for target 'build/sound.rel' failed

maybe a new model?
Best Regards Tony and thank you in advance for helping.

**Comment by aFewBits** [comment]
Sorry for the lapse. 

You have the same model board I have. The error has been corrected in the latest commit, it crept in when some files where changed and the sound board configuration was never tested. Looking into ways to do this, investigating SCON due to its use on another project I'm working on.
